---
# tasks file for docker-registy
- name: log into docker hub regitry
  docker_login:
   email: "farah.ayari1@esprit.tn"
   username: "farahayari"
   password: "203JFT0527"
   
- name: tag and push to docker hub
  docker_image:
   name: angularprojforcd:latest
   repository: farahayari/cdproject
   push: yes
   source: local
