--
# tasks file for docker-registy
- name: log into docker hub regitry
  shell: docker login -u farahayari -p 203JFT0527
   
- name: tag and push to docker hub
  docker_image:
   name: angularprojforcd:latest
   repository: farahayari/cdproject
   push: yes
   source: local
 
