---
# tasks file for docker-registy

- name: register image
  shell: docker image tag angularprojforcd:latest farahayari/cdproject/ngularprojforcd:latest
  shell: docker image push farahayari/cdproject/ngularprojforcd:latest
